### ISSUE TITLE
После прерывания печати голова может пройти слишком низко

### ISSUE THREAD

**Issue by ursoft** [ursoft/Marlin#13]
Поскольку подскока головы при abort нет, то горячая голова с (возможно) соплёй может немного наделать делов.

**Comment by ursoft** [comment]
Каплю все равно на модели оставляет. Но если через паузу - то хоть и не сразу останавливает печать, зато поверхность норм.

**Comment by ssavickiy** [comment]
если стопается печать, то по идее уже не важно, что там с моделью будет.

**Comment by ursoft** [comment]
Согласен, но почему 32-битная плата так тормозит - тоже непонятно. В коде я ничего плохого не нашел, видимо такая синхронизация потоков.
