### ISSUE TITLE
Поэкспериментировать с LinearAdvance

### ISSUE THREAD

**Issue by ursoft** [ursoft/Marlin#17]
понять, за что его так хвалят

**Comment by ssavickiy** [comment]
можно просто включить его в прошивке с нулевым значением, а подбирать будет пользователь, менять черех curа если надо
https://youtu.be/Tykdizutf5Q?t=425

**Comment by ursoft** [comment]
Для  FDPLAST PLA получил K=0.95, ретракт при этом удалось уменьшить с 5.5 до 3.

**Comment by ursoft** [comment]
Однако для стокового применения вариант не годится, ибо требует обязательной переконфигурации драйверов на UART, т.е. аппаратного вмешательства. Чтобы минимизировать площадь проблемы, утаскиваю включение в собственный конфиг.

**Comment by ursoft** [comment]
#19
