### ISSUE TITLE
время таймаута подменю

### ISSUE THREAD

**Issue by ssavickiy** [ursoft/Marlin#21]
при переходе в подменю, выход на главный экран происходит автоматически через N секунд. это не всегда удобно

**Comment by ssavickiy** [comment]
// The timeout (in ms) to return to the status screen from sub-menus
#define LCD_TIMEOUT_TO_STATUS 60000

**Comment by ursoft** [comment]
Меня тоже немного напрягает, там не более 15с сейчас. Вернусь домой в конце недели, поэкспериментирую.
