### ISSUE TITLE
Не сохраняется цвет 12864 (по умолчанию).

### ISSUE THREAD

**Issue by ursoft** [ursoft/Marlin#33]
в Марлине такое сохранение не предусмотрено. Однако существует команда M150, которая устанавливает это значение - т.е. не так уж и сложно было бы сохранять его в EEPROM (по аналогии с другими сохранениями).

**Comment by ssavickiy** [comment]
делал сохранение настроек в епром, после смены цвета, но кажется не сработало. надо проверить

**Comment by ursoft** [comment]
не пишутся они, это 100%

**Comment by ursoft** [comment]
Добавление их в EEPROM буду делать по символу **#define NEOPIXEL_EEPROM_STORE_HACK** в свободное место (которое оттяпаю у тринамиков - там есть пространство, у экструдеров E4 & E5).

**Comment by ursoft** [comment]
onHeatingDone -> leds.set_white
onPrintCompleted -> leds.set_green
onHotendHeating & onBedHeating & onPidTuningDone -> от розового до фиолетового

**Comment by ursoft** [comment]
Стабильность подсветки экрана как-то захотелось. Пусть Марлин развлекается с оставшимися светодиодами.
