### ISSUE TITLE
После успешной печати предложить повторить

### ISSUE THREAD

**Issue by ursoft** [ursoft/Marlin#4]
Если отмена (выделено по умолчанию), показать список файлов (последний напечатанный выделить, если это не затратно).

**Comment by ilmen** [comment]
вывести время предыдущей печати (если не затратно)?

**Comment by ursoft** [comment]
Хорошая мысль, выведем конечно

**Comment by ursoft** [comment]
SD_REPRINT_LAST_SELECTED_FILE работает немного не так, как написано в запросе - но уже хоть что-то. Доработать ее немного, и будет ОК.

**Comment by ursoft** [comment]
Отключил заодно предупреждение о начале печати. Оно нужно только в #3 - там и сделаем.
