### ISSUE TITLE
Файл прошивки firmware.bin

### ISSUE THREAD

**Issue by akaChewy** [ursoft/Marlin#48]
Так как этот форк для определённого принтера (Ulti Steel SKR 1.3 Fysetc Mini 12864).
Почему бы не добавить файл прошивки?

**Comment by ursoft** [comment]
В первую очередь - он для программистов, которые сами себе конфигурацию настроят и соберут прошивку. Принтер развивается: меняются типы драйверов, например. Предсобранные прошивки брать у производителя.
