### ISSUE TITLE
Печать с внутренней карты MicroSD

### ISSUE THREAD

**Issue by ursoft** [ursoft/Marlin#5]
При USB-соединении с принтером доступна эта карта. Скорость записи почти мегабайт в секунду. Возможно, захочется gcode туда засылать. Осталось заставить оттуда распечатать - SDCARD_CONNECTION ONBOARD, но так, чтобы LCD не потерять.

**Comment by fixid-pub** [comment]
Это плохая идея, внутренняя карта нужна для обновления прошивки. Туда достаточно записать firmware.bin для автоматического обновления. Octoprint может обновлять прошивку путем монтирования карты и закидывания бинарника прошивки

**Comment by ursoft** [comment]
если сломается обновление прошивки, то ничего делать не будем, конечно

**Comment by ursoft** [comment]
Обновление прошивки не ломается, но и одновременной работы не предусмотрено. Т.е. если таки доработать marlin для работы с 2 картами, то подав M21/M22 можно внутреннюю смонтировать/отмонтировать. Когда отмонтирована - доступна через USB с ПК. В любом состоянии можно запускать печать из pronterface (сам смонтирует). Самый большой минус - в прошивке не предусмотрена одновременная работа с 2 картами, а если и предусмотреть, это скушает немало памяти и работы не так мало, как в других запросах. Так что, возможно, и не стоит овчинка выделки. Время покажет.

**Comment by ssavickiy** [comment]
имхо, я не вижу смысла в этой фишке.

**Comment by ursoft** [comment]
Такая функция у меня в стоковом дримере была. Прямо из слайсера файл отправлялся по USB на ту флешку, что в материнке торчит (и тут же сам запускался). Удобно, комп можно выключить и никаких тебе расходов на малинку или дерганий SDCARD из разъёма в разъём. Тут же я наверное таки проленюсь это самолично делать (к тому же мне-то малинка приедет скоро, а остальные приучены к своим способам, а не избалованы, как я). Я надеюсь, в исходном репозитории марлина рано или поздно это сделают, раз техническая возможность имеется - может тогда и подтянем.

**Comment by ssavickiy** [comment]
@ursoft малинка умеет на сд карту кидать, но как дальше печать происходит не проверял. наверное можно тогда и малину отрубить

**Comment by ursoft** [comment]
@ssavickiy если она кидает файл командами GCODE через эмуляцию USB<->RS-232 - то да, можно ее потом отключить. Но наверное лучше все же с нее и печатать, чтобы избежать лишней задержки на предварительную передачу файла по USB-каналу 100-200кБит. У дримера-то был полноценный по скорости канал на внутреннюю флешку - а тут будет куцый на внешнюю.

**Comment by ssavickiy** [comment]
@ursoft столкнулся с тем, что все таки это опция должна быть включена SDCARD_CONNECTION ONBOARD
для того, чтобы была возможность через октопринт прошивать плату. но я не пойму, при этом поломается печать с сд карты экрана?

**Comment by ssavickiy** [comment]
update
сейчас прошился через октопринт и без этой опции. хотя в самой инструкции указано https://github.com/OctoPrint/OctoPrint-FirmwareUpdater#lpc1768-boards

**Comment by ursoft** [comment]
В инструкции опечатка, они должны были написать LCD вместо ONBOARD (это действительно значение по умолчанию). Сами же потом монтируют диск по USB. Если таки доделаем запрос, то октопринт сможет на высокой скорости записывать задание на печать по USB, а потом хоть помирать.

**Comment by ursoft** [comment]
Вот какой получается алгоритм (включается SDCARD_CONNECTION=LCD_AND_ONBOARD и предполагает наличие внутренней карты, иначе не имеет смысла):
1. Монтаж карты осуществляется в следующем приоритете: внешняя карта важнее, но если ее нет, смонтируется внутренняя.
2. На старте монтируем карту согласно п1, чтобы проверить, есть ли auto#.g или recovery. Если есть, отрабатываем их и по возможности демонтируем внутреннюю карту (чтобы была видна в ПК как USB-диск). Иначе обязательно демонтируем внутреннюю. Если не демонтировалась, это можно сделать командой M22 (или из меню) - и можно заливать с ПК прошивку или gcode.
3. Если какие-то действия пользователя привели к монтажу внутренней карты, автоматически она потом не демонтируется.
4. Если какие-то действия пользователя привели к монтажу внешней карты, автоматически демонтируется внутренняя.

**Comment by ssavickiy** [comment]
Firmware Updater перестал работать на октопринте, причин пока не вижу
UPD
помогло добавление следующих строк в /lib/systemd/system/systemd-udevd.service 
####
PrivateMounts=no
MountFlags=shared
####

**Comment by ursoft** [comment]
Спасибо, я и забыл написать про PrivateMounts

**Comment by ursoft** [comment]
Откатил временно, костыль конфликтует с включением режима UART

**Comment by ursoft** [comment]
теперь порядок
