### ISSUE TITLE
Sir 1.3

### ISSUE THREAD

**Issue by sir90ha** [ursoft/Marlin#52]
Доброго дня ч чате по 3д мне не могут помочь, решил сюда написать.. в чем может быть проблема?
Конфигурация:
But skr1.3
TMC 2209 UART
База Ultimaker 2

Проблема такова: 
При попытки выдавливания пластика экструдер издает звук и мотор больше не отвечает на команды при перезагрузке ошибка повторяется, драйвера рабочие, моторы то же.

**Comment by ursoft** [comment]
Точно TMC 2209, а не 2208 ? Именно 2208 любят уходить, если им что не нравится, в защиту - а в 2209 ЕМНИП это исправили. Хотя могли позабыть и снова испортить.
У 2208 проблема "решалась" либо смягчением ретрактов (вплоть до отказа от них), либо сменой режима StealthChop на SpreadCycle. В кавычках, т.к. это было не решение проблемы, а уменьшение вероятности её возникновения.
А вообще шибко умные драйверы, которые умеют уходить в защиту от частых и резких смен направления, не следует ставить на экструдер.
