### ISSUE TITLE
Двойное/долгое нажатие в главном меню

### ISSUE THREAD

**Issue by ursoft** [ursoft/Marlin#6]
При наличии SD карты и скрипта long_cli.g на ней, выполнить его. Иначе предварительный нагрев первого материала в списке.

**Comment by ilmen** [comment]
Почему именно PLA?
Может переход в меню выбора профиля преднагрева?

**Comment by ursoft** [comment]
Наверное конкретное действие будет выбираться в конфигурации, в моей будет самое частое для меня. Если мне открывать меню, то для завершения операции требуется еще куча действий - теряются несколько секунд и надо смотреть на экран. А так я нащупаю кнопку и зажму, она пискнет.

**Comment by ursoft** [comment]
Итого вот что получается: долгое нажатие от двойного отличать там не умеют, а мы обучать не будем. При печати это занято на BabyStepping - и так останется. А вот при ожидании начинается наша петрушка:
1. Принтер издаёт мерзкий писк и ждет после него секунду. Если Вы попали сюда случайно, до истечения этой секунды Вам следует испугаться и отжать кнопку. В этом случае ничего больше не произойдет. 
2. Кнопку держите - значит, знаете, зачем. Ищет в корне флешки файл long_cli.g и, если найден, выполняет его (на этом заканчивает).
3.  Со вторым писком можете кнопку отжать уже. Если после второго писка идет третий - значит, Вы включили предварительный прогрев под первый материал. Если третьего нет - значит, у Вас до этого был некий прогрев - а теперь Вы его выключили.
