### ISSUE TITLE
Крутилка в главном меню (в режиме ожидания, не печати)

### ISSUE THREAD

**Issue by ursoft** [ursoft/Marlin#7]
Увеличивает/уменьшает FR (feed rate). Полный бред. Лучше пусть файлы покажет.

**Comment by fixid-pub** [comment]
Не все печатают с SD карточки

**Comment by ursoft** [comment]
Если карты нет, можно что-то другое делать (меню глубокое достать, а то и два). А можно это дело на конфигурацию посадить. Сдается мне, что FR на крутилке во время печати - к месту, а вот в состоянии простоя лучше как-то иначе использовать.
