### ISSUE TITLE
Редакторы значений

### ISSUE THREAD

**Issue by ursoft** [ursoft/Marlin#8]
Крутить от default 0 - то еще удовольствие, придумать лучшие default

**Comment by akaChewy** [comment]
Не сильно критично, но для удобства предлагаю отслеживать не перешел ли энкодер в режим 10x speed, или 100x speed
#define ENCODER_10X_STEPS_PER_SEC   30  // (steps/s) Encoder rate for 10x speed
#define ENCODER_100X_STEPS_PER_SEC  80  // (steps/s) Encoder rate for 100x speed
и в этом случае не крутить значения по кругу, а упираться в минимальное, или максимальное значение, в зависимости от направления вращения.

**Comment by ursoft** [comment]
Годное улучшение, спасибо. Можно тестировать.
